Um, deploy?

diff --git a/bin/cf-branch-build b/bin/cf-branch-build
--- a/bin/cf-branch-build
+++ b/bin/cf-branch-build
@@ -9,3 +9,35 @@ set -o pipefail
 set -x
 
 echo $CF_BRANCH_NAME
+
+# if [ $# -ne 1 ]; then
+#   echo "Usage:\n\n\t./cf-branch-build <appname>\n"
+#   exit 1
+# fi
+
+finally ()
+{
+  # we don't want to keep the sensitive information around
+  rm $MANIFEST
+}
+
+on_fail () {
+  finally
+  echo "DEPLOY FAILED - you may need to check 'cf apps' and 'cf routes' and do manual cleanup"
+}
+
+# Set up try/catch
+trap on_fail ERR
+
+# Create Manifest
+MANIFEST=$(cat manifest.yml)
+DOMAIN=$(cat $MANIFEST | grep domain: | awk '{print $2}')
+
+# Create BRANCH application
+cf push $CF_BRANCH_NAME -f $MANIFEST -n $CF_BRANCH_NAME
+# ensure it starts
+curl --fail -I "https://${CF_BRANCH_NAME}.${DOMAIN}"
+
+finally
+
+echo "DONE"
